version: '3.8'

services:
  # PHP Apache Service
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: twig-ticket-app
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
      - ./data:/var/www/html/data
    environment:
      - PHP_DISPLAY_ERRORS=1
      - PHP_ERROR_REPORTING=E_ALL
    depends_on:
      - db
    networks:
      - app-network

  # Database Service (Optional - for future database integration)
  db:
    image: mysql:8.0
    container_name: twig-mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: ticket_app
      MYSQL_USER: ticket_user
      MYSQL_PASSWORD: ticket_password
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - app-network

  # phpMyAdmin (Optional - for database management)
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: twig-phpmyadmin
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: rootpassword
      MYSQL_ROOT_PASSWORD: rootpassword
    ports:
      - "8081:80"
    depends_on:
      - db
    networks:
      - app-network

volumes:
  mysql-data:
    driver: local

networks:
  app-network:
    driver: bridge
